repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [backend/meetball/src, --fix]

      - id: ruff-format
        types: [python]
        args: [backend/meetball/src]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        pass_filenames: false
        files: ''
        args: [--config-file=backend/meetball/pyproject.toml, backend/meetball/src]