version: '3'

tasks:
  lint_mb:
    cmds:
      - isort backend/meetball/src
      - autoflake --in-place -r backend/meetball/src
      - black backend/meetball/src
      - ruff check backend/meetball/src --fix
      - mypy --config-file=backend/meetball/pyproject.toml backend/meetball/src