version: '3'

tasks:
  lint_mb:
    cmds:
      - ruff check backend/meetball/src --fix
      - ruff format backend/meetball/src
      - mypy --config-file=backend/meetball/pyproject.toml backend/meetball/src